
services:
  backend:
    build:
      context: .
      dockerfile: configs/Dockerfile.backend
    container_name: quickpost-backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./src/js:/app/src/js
    depends_on:
      - mongo
    networks:
      - quickpost-network

  frontend:
    build:
      context: .
      dockerfile: configs/Dockerfile.frontend
    container_name: quickpost-frontend
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - quickpost-network

  mongo:
    image: mongo:5.0
    container_name: quickpost-mongo
    ports:
      - "27017:27017"
    networks:
      - quickpost-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  quickpost-network:
    driver: bridge
