
services:
  backend:
    build:
      context: .
      dockerfile: configs/Dockerfile.backend
    container_name: quickpost-backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./src/js:/app/src/js
    networks:
      - quickpost-network

  frontend:
    build:
      context: .
      dockerfile: configs/Dockerfile.frontend
    container_name: quickpost-frontend
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - quickpost-network

networks:
  quickpost-network:
    driver: bridge
