name: Ejecutar Servidor Node.js

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest 

    steps:
    - name: Verificar el repositorio
      uses: actions/checkout@v3 

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Configurar variables de entorno
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env 

    - name: Ejecutar servidor Node.js
      run: |
        node src/js/index.js 

    - name: Detener servidor después de la ejecución
      run: |
        kill $(lsof -t -i:$(lsof -t -i:5000)) 
